### ISSUE TITLE
Algorithm to create batches

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/GenerateMatchedDataset#2]
dear @DavideMessinaARS, @stefano-lodi and @ersiliaL,

i reported [here](https://github.com/ARS-toscana/GenerateMatchedDataset/wiki/Use-of-the-threshold) the basic description of how the threshold is used in matching (and bootstrapping). 

i did not specify how the batches are created, after @DavideMessinaARS mentioned that pure grouping according to frequency may be infefficient.

@DavideMessinaARS you could use this issue to explain the problem and how you plan to address it

**Comment by DavideMessinaARS** [comment]
This issue was opened after I noticed an exponential increase in the computation time, compared to initial testings, of calls to the function using threshold and multiple exact/range variables. I later discovered the bug was caused by a different problem which I have already fixed.

Regarding the bug above, firstly I hypothesized that more internally homogeneous batches would be simpler for data.table to process leading to a decrease in time. Using 1 exact/range variable the function was working correctly and the batches were assured to be mostly homogeneous.

I created a "fix" by sorting the dataset with the frequencies of combinations by exact/range variables and by the total frequencies. This dataset would then be passed through the bin-packing algorithm.

The "fix" was not a solution to the initial issue but I was still curious to see if it had any impact whatsoever so I ran a batch of experiments with and without the "fix".

## Results

### Time

| ![](https://github.com/ARS-toscana/GenerateMatchedDataset/assets/78373669/320d6699-b421-44ec-a4c5-240c33489f84) | 
|:--:| 
| *Vertical lines indicate the range between the minimum and maximum time of all replications of an experiment.
Points are the median of each experiment* |

The is no significant difference in my opinion regarding computation time

### RAM

![](https://github.com/ARS-toscana/GenerateMatchedDataset/assets/78373669/17932af8-967f-4f44-8879-b24f7ffcdffb)

The difference might be there and it is consistent but it is only around 2-2.5% less RAM utilization. I think then it is not worth it. At least for now.
("might be there" since tracking memory usage in data.table might not be exact)

I will revert the function to using the "standard" method
